def populate_entity_list() -> dict:
    """
    Return a dictionary of INSERT SQL statement.

    Return a dictionary of INSERT SQL statement for the entity_parameters
    table.

    Args:
        None

    Returns:
        Dictionary: a dictionary of INSERT SQL statements.
    """

    entity_params = {
        "adventureworks": """
            INSERT INTO [ods_adventureworks].[entity_params] (
                table_name
                ,entity_name
                ,business_key
                ,modified_field
                ,load_method
                ,chunksize
                ,active
            )

            VALUES (
                'Department'
                ,'HumanResources.Department'
                ,'DepartmentID'
                ,'ModifiedDate'
                ,'incremental'
                ,NULL
                ,1
            )
            ,(
                -- sql_variant datatype can't be read via ODBC
                'Employee'
                ,'HumanResources.Employee'
                ,'BusinessEntityID'
                ,'ModifiedDate'
                ,'incremental'
                ,NULL
                ,0
            )
            ,(
                'EmployeeDepartmentHistory'
                ,'HumanResources.EmployeeDepartmentHistory'
                ,'BusinessEntityID'
                ,'ModifiedDate'
                ,'incremental'
                ,NULL
                ,1
            )
            ,(
                'EmployeePayHistory'
                ,'HumanResources.EmployeePayHistory'
                ,'BusinessEntityID'
                ,'ModifiedDate'
                ,'incremental'
                ,NULL
                ,1
            )
            ,(
                'JobCandidate'
                ,'HumanResources.JobCandidate'
                ,'JobCandidateID'
                ,'ModifiedDate'
                ,'incremental'
                ,NULL
                ,1
            )
            ,(
                'Shift'
                ,'HumanResources.Shift'
                ,'ShiftID'
                ,'ModifiedDate'
                ,'incremental'
                ,NULL
                ,1
            )
            ,(
                -- sql_variant datatype can't be read via ODBC
                'Address'
                ,'Person.Address'
                ,'AddressID'
                ,'ModifiedDate'
                ,'incremental'
                ,NULL
                ,0
            )
            ,(
                'AddressType'
                ,'Person.AddressType'
                ,'AddressTypeID'
                ,'ModifiedDate'
                ,'incremental'
                ,NULL
                ,1
            )
            ,(
                'BusinessEntity'
                ,'Person.BusinessEntity'
                ,'BusinessEntityID'
                ,'ModifiedDate'
                ,'incremental'
                ,NULL
                ,1
            )
            ,(
                'BusinessEntityAddress'
                ,'Person.BusinessEntityAddress'
                ,'BusinessEntityID'
                ,'ModifiedDate'
                ,'incremental'
                ,NULL
                ,1
            )
            ,(
                'BusinessEntityContact'
                ,'Person.BusinessEntityContact'
                ,'BusinessEntityID'
                ,'ModifiedDate'
                ,'incremental'
                ,NULL
                ,1
            )
            ,(
                'ContactType'
                ,'Person.ContactType'
                ,'ContactTypeID'
                ,'ModifiedDate'
                ,'incremental'
                ,NULL
                ,1
            )
            ,(
                'CountryRegion'
                ,'Person.CountryRegion'
                ,'CountryRegionCode'
                ,'ModifiedDate'
                ,'incremental'
                ,NULL
                ,1
            )
            ,(
                'EmailAddress'
                ,'Person.EmailAddress'
                ,'BusinessEntityID'
                ,'ModifiedDate'
                ,'incremental'
                ,NULL
                ,1
            )
            ,(
                'Password'
                ,'Person.Password'
                ,'BusinessEntityID'
                ,'ModifiedDate'
                ,'incremental'
                ,NULL
                ,1
            )
            ,(
                'Person'
                ,'Person.Person'
                ,'BusinessEntityID'
                ,'ModifiedDate'
                ,'incremental'
                ,NULL
                ,1
            )
            ,(
                'PersonPhone'
                ,'Person.PersonPhone'
                ,'BusinessEntityID'
                ,'ModifiedDate'
                ,'incremental'
                ,NULL
                ,1
            )
            ,(
                'PhoneNumberType'
                ,'Person.PhoneNumberType'
                ,'PhoneNumberTypeID'
                ,'ModifiedDate'
                ,'incremental'
                ,NULL
                ,1
            )
            ,(
                'StateProvince'
                ,'Person.StateProvince'
                ,'StateProvinceID'
                ,'ModifiedDate'
                ,'incremental'
                ,NULL
                ,1
            )
            ,(
                'BillOfMaterials'
                ,'Production.BillOfMaterials'
                ,'BillOfMaterialsID'
                ,'ModifiedDate'
                ,'incremental'
                ,NULL
                ,1
            )
            ,(
                'Culture'
                ,'Production.Culture'
                ,'CultureID'
                ,'ModifiedDate'
                ,'incremental'
                ,NULL
                ,1
            )
            ,(
                -- sql_variant datatype can't be read via ODBC
                'Document'
                ,'Production.Document'
                ,'DocumentNode'
                ,'ModifiedDate'
                ,'incremental'
                ,NULL
                ,0
            )
            ,(
                'Illustration'
                ,'Production.Illustration'
                ,'IllustrationID'
                ,'ModifiedDate'
                ,'incremental'
                ,NULL
                ,1
            )
            ,(
                'Location'
                ,'Production.Location'
                ,'LocationID'
                ,'ModifiedDate'
                ,'incremental'
                ,NULL
                ,1
            )
            ,(
                'Product'
                ,'Production.Product'
                ,'ProductID'
                ,'ModifiedDate'
                ,'incremental'
                ,NULL
                ,1
            )
            ,(
                'ProductCategory'
                ,'Production.ProductCategory'
                ,'ProductCategoryID'
                ,'ModifiedDate'
                ,'incremental'
                ,NULL
                ,1
            )
            ,(
                'ProductCostHistory'
                ,'Production.ProductCostHistory'
                ,'ProductID'
                ,'ModifiedDate'
                ,'incremental'
                ,NULL
                ,1
            )
            ,(
                'ProductDescription'
                ,'Production.ProductDescription'
                ,'ProductDescriptionID'
                ,'ModifiedDate'
                ,'incremental'
                ,NULL
                ,1
            )
            ,(
                -- sql_variant datatype can't be read via ODBC
                'ProductDocument'
                ,'Production.ProductDocument'
                ,'ProductID'
                ,'ModifiedDate'
                ,'incremental'
                ,NULL
                ,0
            )
            ,(
                'ProductInventory'
                ,'Production.ProductInventory'
                ,'ProductID'
                ,'ModifiedDate'
                ,'incremental'
                ,NULL
                ,1
            )
            ,(
                'ProductListPriceHistory'
                ,'Production.ProductListPriceHistory'
                ,'ProductID'
                ,'ModifiedDate'
                ,'incremental'
                ,NULL
                ,1
            )
            ,(
                'ProductModel'
                ,'Production.ProductModel'
                ,'ProductModelID'
                ,'ModifiedDate'
                ,'incremental'
                ,NULL
                ,1
            )
            ,(
                'ProductModelIllustration'
                ,'Production.ProductModelIllustration'
                ,'ProductModelID'
                ,'ModifiedDate'
                ,'incremental'
                ,NULL
                ,1
            )
            ,(
                'ProductModelProductDescriptionCulture'
                ,'Production.ProductModelProductDescriptionCulture'
                ,'ProductModelID'
                ,'ModifiedDate'
                ,'incremental'
                ,NULL
                ,1
            )
            ,(
                'ProductProductPhoto'
                ,'Production.ProductProductPhoto'
                ,'ProductID'
                ,'ModifiedDate'
                ,'incremental'
                ,NULL
                ,1
            )
            ,(
                'ProductReview'
                ,'Production.ProductReview'
                ,'ProductReviewID'
                ,'ModifiedDate'
                ,'incremental'
                ,NULL
                ,1
            )
            ,(
                'ProductSubcategory'
                ,'Production.ProductSubcategory'
                ,'ProductSubcategoryID'
                ,'ModifiedDate'
                ,'incremental'
                ,NULL
                ,1
            )
            ,(
                'ScrapReason'
                ,'Production.ScrapReason'
                ,'ScrapReasonID'
                ,'ModifiedDate'
                ,'incremental'
                ,NULL
                ,1
            )
            ,(
                'TransactionHistory'
                ,'Production.TransactionHistory'
                ,'TransactionID'
                ,'ModifiedDate'
                ,'incremental'
                ,NULL
                ,1
            )
            ,(
                'TransactionHistoryArchive'
                ,'Production.TransactionHistoryArchive'
                ,'TransactionID'
                ,'ModifiedDate'
                ,'incremental'
                ,NULL
                ,1
            )
            ,(
                'UnitMeasure'
                ,'Production.UnitMeasure'
                ,'UnitMeasureCode'
                ,'ModifiedDate'
                ,'incremental'
                ,NULL
                ,1
            )
            ,(
                'WorkOrder'
                ,'Production.WorkOrder'
                ,'WorkOrderID'
                ,'ModifiedDate'
                ,'incremental'
                ,NULL
                ,1
            )
            ,(
                'WorkOrderRouting'
                ,'Production.WorkOrderRouting'
                ,'WorkOrderID'
                ,'ModifiedDate'
                ,'incremental'
                ,NULL
                ,1
            )
            ,(
                'ProductVendor'
                ,'Purchasing.ProductVendor'
                ,'ProductID'
                ,'ModifiedDate'
                ,'incremental'
                ,NULL
                ,1
            )
            ,(
                'PurchaseOrderDetail'
                ,'Purchasing.PurchaseOrderDetail'
                ,'PurchaseOrderID'
                ,'ModifiedDate'
                ,'incremental'
                ,NULL
                ,1
            )
            ,(
                'PurchaseOrderHeader'
                ,'Purchasing.PurchaseOrderHeader'
                ,'PurchaseOrderID'
                ,'ModifiedDate'
                ,'incremental'
                ,NULL
                ,1
            )
            ,(
                'ShipMethod'
                ,'Purchasing.ShipMethod'
                ,'ShipMethodID'
                ,'ModifiedDate'
                ,'incremental'
                ,NULL
                ,1
            )
            ,(
                'Vendor'
                ,'Purchasing.Vendor'
                ,'BusinessEntityID'
                ,'ModifiedDate'
                ,'incremental'
                ,NULL
                ,1
            )
            ,(
                'CountryRegionCurrency'
                ,'Sales.CountryRegionCurrency'
                ,'CountryRegionCode'
                ,'ModifiedDate'
                ,'incremental'
                ,NULL
                ,1
            )
            ,(
                'CreditCard'
                ,'Sales.CreditCard'
                ,'CreditCardID'
                ,'ModifiedDate'
                ,'incremental'
                ,NULL
                ,1
            )
            ,(
                'Currency'
                ,'Sales.Currency'
                ,'CurrencyCode'
                ,'ModifiedDate'
                ,'incremental'
                ,NULL
                ,1
            )
            ,(
                'CurrencyRate'
                ,'Sales.CurrencyRate'
                ,'CurrencyRateID'
                ,'ModifiedDate'
                ,'incremental'
                ,NULL
                ,1
            )
            ,(
                'Customer'
                ,'Sales.Customer'
                ,'CustomerID'
                ,'ModifiedDate'
                ,'incremental'
                ,NULL
                ,1
            )
            ,(
                'PersonCreditCard'
                ,'Sales.PersonCreditCard'
                ,'BusinessEntityID'
                ,'ModifiedDate'
                ,'incremental'
                ,NULL
                ,1
            )
            ,(
                'SalesOrderDetail'
                ,'Sales.SalesOrderDetail'
                ,'SalesOrderID'
                ,'ModifiedDate'
                ,'incremental'
                ,NULL
                ,1
            )
            ,(
                'SalesOrderHeader'
                ,'Sales.SalesOrderHeader'
                ,'SalesOrderID'
                ,'ModifiedDate'
                ,'incremental'
                ,NULL
                ,1
            )
            ,(
                'SalesOrderHeaderSalesReason'
                ,'Sales.SalesOrderHeaderSalesReason'
                ,'SalesOrderID'
                ,'ModifiedDate'
                ,'incremental'
                ,NULL
                ,1
            )
            ,(
                'SalesPerson'
                ,'Sales.SalesPerson'
                ,'BusinessEntityID'
                ,'ModifiedDate'
                ,'incremental'
                ,NULL
                ,1
            )
            ,(
                'SalesPersonQuotaHistory'
                ,'Sales.SalesPersonQuotaHistory'
                ,'BusinessEntityID'
                ,'ModifiedDate'
                ,'incremental'
                ,NULL
                ,1
            )
            ,(
                'SalesReason'
                ,'Sales.SalesReason'
                ,'SalesReasonID'
                ,'ModifiedDate'
                ,'incremental'
                ,NULL
                ,1
            )
            ,(
                'SalesTaxRate'
                ,'Sales.SalesTaxRate'
                ,'SalesTaxRateID'
                ,'ModifiedDate'
                ,'incremental'
                ,NULL
                ,1
            )
            ,(
                'SalesTerritory'
                ,'Sales.SalesTerritory'
                ,'territoryid'
                ,'ModifiedDate'
                ,'incremental'
                ,NULL
                ,1
            )
            ,(
                'SalesTerritoryHistory'
                ,'Sales.SalesTerritoryHistory'
                ,'BusinessEntityID'
                ,'ModifiedDate'
                ,'incremental'
                ,NULL
                ,1
            )
            ,(
                'ShoppingCartItem'
                ,'Sales.ShoppingCartItem'
                ,'ShoppingCartItemID'
                ,'ModifiedDate'
                ,'incremental'
                ,NULL
                ,1
            )
            ,(
                'SpecialOffer'
                ,'Sales.SpecialOffer'
                ,'SpecialOfferID'
                ,'ModifiedDate'
                ,'incremental'
                ,NULL
                ,1
            )
            ,(
                'SpecialOfferProduct'
                ,'Sales.SpecialOfferProduct'
                ,'SpecialOfferID'
                ,'ModifiedDate'
                ,'incremental'
                ,NULL
                ,1
            )
            ,(
                'Store'
                ,'Sales.Store'
                ,'BusinessEntityID'
                ,'ModifiedDate'
                ,'incremental'
                ,NULL
                ,1
            )
        ;""",
    }

    return entity_params
